# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
AppDir:
  path: AppDir
  app_info:
    id: com.owokitty.Saturn
    name: Saturn
    icon: application-vnd.appimage
    version: latest
    exec: saturn.us.f3dex2e
    exec_args: $@
  apt:
    arch:
    - amd64
    sources:
    - sourceline: deb https://us.archive.ubuntu.com/ubuntu/ mantic main
    - sourceline: deb https://us.archive.ubuntu.com/ubuntu/ mantic-updates main
    - sourceline: deb https://us.archive.ubuntu.com/ubuntu/ mantic-backports main
    - sourceline: deb https://security.ubuntu.com/ubuntu mantic-security main
    INclude:
    - libc6:amd64
    - libsdl2
    - libgtk-4
  files:
    include: []
    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
AppImage:
  arch: x86_64
  update-information: guess